name: "jaffle_shop"

config-version: 2
version: "0.1"

profile: "jaffle_shop"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

seeds:
  jaffle_shop:
    # +schema: raw
    +docs:
      node_color: "#cd7f32"
    # Explicit column types for seeds to avoid CSV conversion errors when values include
    # decimals or exceed INTEGER bounds. Adjust per-column as needed.
    films:
      +column_types:
        release_year: DOUBLE
        duration: DOUBLE
        gross: DOUBLE
        budget: DOUBLE

    reviews:
      +strict_mode: false
      +delimiter: ","
      +quote: '"'
      +escape: '\'

models:
  jaffle_shop:
    +materialized: table
    staging:
      +materialized: view
      +docs:
        node_color: "silver"
    +docs:
      node_color: "gold"
